general {
    lock_cmd = pidof hyprlock || hyprlock       # 防止启动多个 hyprlock 实例。
    before_sleep_cmd = loginctl lock-session    # 休眠前锁定。
    after_sleep_cmd = hyprctl dispatch dpms on  # 避免需要按两次键才能打开显示器。
}

listener {
    timeout = 600                                # 2.5分钟。
    on-timeout = brightnessctl -s set 10         # 将显示器亮度设置为最低，避免 OLED 显示器亮度为 0。
    on-resume = brightnessctl -r                 # 恢复显示器亮度。
}

# 关闭键盘背光，如果没有键盘背光，可以注释掉此部分。
listener { 
    timeout = 600                                          # 2.5分钟。
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # 关闭键盘背光。
    on-resume = brightnessctl -rd rgb:kbd_backlight        # 打开键盘背光。
}

listener {
    timeout = 900                                 # 5分钟
    on-timeout = loginctl lock-session            # 超时后锁定屏幕
}

listener {
    timeout = 1200                                 # 5.5分钟
    on-timeout = hyprctl dispatch dpms off        # 超时后关闭屏幕
    on-resume = hyprctl dispatch dpms on          # 检测到活动后，超时触发后打开屏幕。
}

# listener {
#     timeout = 1800                                # 30分钟
#     on-timeout = systemctl suspend                # 使电脑进入休眠
# }

